### ISSUE TITLE
Manually Releasing the Mutex?

### ISSUE THREAD

**Issue by matt-findlay** [ben-z/gh-action-mutex#13]
Github actions had an outage two days ago that left our mutex in a LOCKED state. How can we manually release the lock? This is blocking everything we do now.

**Comment by ben-z** [comment]
Oh no! Go to the lock branch and manually remove the lines in the file that corresponds to the interrupted job. It’s probably the first line if it’s blocking everything.
#4 is open to track one solution to this.

**Comment by matt-findlay** [comment]
Hey @ben-z sorry I don't quite understand. Can you clarify where I can find the 'lock branch'? Are you referring to the branch that triggered the github action? 

Also, can you clarify which file needs the line removed?

Thanks so much. Sorry I am new to github actions and really appreciate your help here as this is blocking me at my job

**Comment by matt-findlay** [comment]
Ok @ben-z I fixed it!
